<a href="https://colab.research.google.com/github/safal207/hello-world/blob/master/Conv2D_Arguments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Conv1D
import numpy as np
import tensorflow as tf

In [ ]:
inp = np.arange(1, 26)
inp = inp.reshape((5,5,1))
print(inp.squeeze())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# filters and kernel_size

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
                kernel_size=(2,2),
                strides=(1, 1),
                padding="valid",
                data_format=None,
                dilation_rate=(1, 1),
                groups=1,
                activation=None,
                use_bias=False,
                kernel_initializer="glorot_uniform",
                bias_initializer="zeros",
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None,
                input_shape=(inp.shape)))
                # **kwargs   

model.compile()
model.summary()

Model: "sequential_44"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 4, 4, 1)           4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]]],
 
 
        [[[2.]],
 
         [[3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[ 35.  41.  47.  53.]
 [ 65.  71.  77.  83.]
 [ 95. 101. 107. 113.]
 [125. 131. 137. 143.]]


In [ ]:
2 + 6 *2 + 7*3

35

In [ ]:
7*0+8*1+12*2+13*3

71

## 3x3

In [ ]:
model = Sequential()
model.add(Conv2D(1, (3,3), use_bias=False, input_shape=inp.shape))
model.compile()

In [ ]:
custom_weights = np.array([[[[0]],[[1]],[[2]]],[[[3]],[[4]],[[5]]],[[[6]],[[7]],[[8]]]])
model.set_weights([custom_weights])

In [ ]:
model.get_weights()

[array([[[[0.]],
 
         [[1.]],
 
         [[2.]]],
 
 
        [[[3.]],
 
         [[4.]],
 
         [[5.]]],
 
 
        [[[6.]],
 
         [[7.]],
 
         [[8.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,1))
print(res.shape)

(1, 3, 3, 1)


In [ ]:
print(res[0].squeeze())

[[348. 384. 420.]
 [528. 564. 600.]
 [708. 744. 780.]]


## 4x4

In [ ]:
model = Sequential()
model.add(Conv2D(1, (4,4), use_bias=False, input_shape=inp.shape, padding='same'))
model.compile()

In [ ]:
custom_weights = np.array([[[[0]],[[1]],[[2]],[[3]]],[[[4]],[[5]],[[6]],[[7]]],[[[8]],[[9]],[[10]],[[11]]],[[[12]],[[13]],[[14]],[[15]]]])
model.set_weights([custom_weights])

In [ ]:
model.get_weights()

[array([[[[ 0.]],
 
         [[ 1.]],
 
         [[ 2.]],
 
         [[ 3.]]],
 
 
        [[[ 4.]],
 
         [[ 5.]],
 
         [[ 6.]],
 
         [[ 7.]]],
 
 
        [[[ 8.]],
 
         [[ 9.]],
 
         [[10.]],
 
         [[11.]]],
 
 
        [[[12.]],
 
         [[13.]],
 
         [[14.]],
 
         [[15.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,1))
print(res.shape)

(1, 5, 5, 1)


In [ ]:
print(res[0].squeeze())

[[ 756. 1030. 1144.  855.  566.]
 [1220. 1620. 1740. 1274.  826.]
 [1700. 2220. 2340. 1694. 1086.]
 [1044. 1330. 1396.  981.  608.]
 [ 502.  610.  638.  421.  241.]]


# strides and padding

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=(2,2),
    padding="same",
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation=None,
    use_bias=False,
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_50"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_33 (Conv2D)           (None, 3, 3, 1)           4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]]],
 
 
        [[[2.]],
 
         [[3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 3, 3, 1) 

[[ 35.  47.  20.]
 [ 95. 107.  40.]
 [ 22.  24.   0.]]


In [ ]:
2 + 6*2+ 7*3

35

In [ ]:
3*0+4*1+8*2+9*3

47

## 3x3

In [ ]:
model = Sequential()
model.add(Conv2D(1, (3,3), use_bias=False, padding="valid", input_shape=inp.shape))
model.compile()

In [ ]:
custom_weights = np.array([[[[0]],[[1]],[[2]]],[[[3]],[[4]],[[5]]],[[[6]],[[7]],[[8]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]],
 
         [[2.]]],
 
 
        [[[3.]],
 
         [[4.]],
 
         [[5.]]],
 
 
        [[[6.]],
 
         [[7.]],
 
         [[8.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 3, 3, 1) 

[[348. 384. 420.]
 [528. 564. 600.]
 [708. 744. 780.]]


In [ ]:
0*0 + 0*1 + 0*2 + 0*3 + 1*4 + 2*5 + 0*6 + 6*7 + 7*8

112

In [ ]:
19*0 + 20*1 + 24*3 +25*4

192

# dilation_rate

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=(1, 1),
    padding="valid",
    data_format=None, # channels_last (default) or channels_first
    dilation_rate=(2, 2),
    groups=1,
    activation=None,
    use_bias=False,
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_51"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_34 (Conv2D)           (None, 3, 3, 1)           4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]]],
 
 
        [[[2.]],
 
         [[3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 3, 3, 1) 

[[ 64.  70.  76.]
 [ 94. 100. 106.]
 [124. 130. 136.]]


In [ ]:
1*0 + 3*1 + 11*2 + 13*3

64

# groups

In [ ]:
inp2 = np.concatenate([inp.squeeze(),inp.squeeze()],axis=0)
inp2 = inp2.reshape(2,5,5)
print(inp2.squeeze())

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]]


In [ ]:
model = Sequential()
model.add(Conv2D(filters = 2,
    kernel_size=(2,2),
    strides=(1, 1),
    padding="valid",
    data_format='channels_first',
    dilation_rate=(1, 1),
    groups=2,
    activation=None,
    use_bias=False,
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp2.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_55"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_38 (Conv2D)           (None, 2, 4, 4)           8         
Total params: 8
Trainable params: 8
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0,0]],[[1,1]]],[[[2,2]],[[3,3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0., 0.]],
 
         [[1., 1.]]],
 
 
        [[[2., 2.]],
 
         [[3., 3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp2.reshape(1,2,5,5))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 2, 4, 4) 

[[[ 34.999996  40.999996  47.        52.999996]
  [ 65.        71.        76.99999   83.      ]
  [ 94.99999  101.       106.999985 112.99999 ]
  [124.999985 131.       137.       143.      ]]

 [[ 34.999996  40.999996  47.        52.999996]
  [ 65.        71.        76.99999   83.      ]
  [ 94.99999  101.       106.999985 112.99999 ]
  [124.999985 131.       137.       143.      ]]]


# activation

In [ ]:
inp_ = np.arange(-9, 16)
inp_ = inp_.reshape((5,5,1))
print(inp_.squeeze())

[[-9 -8 -7 -6 -5]
 [-4 -3 -2 -1  0]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=(1, 1),
    padding="valid",
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation='relu',
    use_bias=False,
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp_.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_56"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_39 (Conv2D)           (None, 4, 4, 1)           4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]]],
 
 
        [[[2.]],
 
         [[3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp_.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[ 0.  0.  0.  0.]
 [ 5. 11. 17. 23.]
 [35. 41. 47. 53.]
 [65. 71. 77. 83.]]


In [ ]:
-9*0+-8*1+-4*2+-3*3

-25

In [ ]:
9*0+10*1+14*2+15*3

83

# use_bias

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=(1, 1),
    padding="valid",
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation=None,
    use_bias=True,
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_57"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_40 (Conv2D)           (None, 4, 4, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
# model.set_weights([custom_weights])
model.get_weights()

[array([[[[-0.5695899 ]],
 
         [[ 0.61981446]]],
 
 
        [[[ 0.02200526]],
 
         [[ 0.562964  ]]]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[1.8111485 2.1593623 2.5075762 2.8557901]
 [3.5522177 3.9004316 4.2486453 4.5968595]
 [5.293287  5.641501  5.9897146 6.337929 ]
 [7.034356  7.3825703 7.730784  8.078998 ]]


# kernel_initializer and bias_initializer

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=(1, 1),
    padding="valid",
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation=None,
    use_bias=True,
    kernel_initializer="Ones", # RandomNormal, RandomUniform, TruncatedNormal, Glorot_uniform
                                         # Zeros, Ones, GlorotNormal, Identity, Orthogonal, 
                                         # Constant, VarianceScaling, custom
    bias_initializer="Ones",            
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    input_shape=(inp.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_60"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_43 (Conv2D)           (None, 4, 4, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
# model.set_weights([custom_weights])
model.get_weights()

[array([[[[1.]],
 
         [[1.]]],
 
 
        [[[1.]],
 
         [[1.]]]], dtype=float32), array([1.], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[17. 21. 25. 29.]
 [37. 41. 45. 49.]
 [57. 61. 65. 69.]
 [77. 81. 85. 89.]]


In [ ]:
1 + 2 +6 + 7


16

# kernel_regularizer and bias_regularizer and activity_regularizer

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
                kernel_size=(2,2),
                strides=(1, 1),
                padding="valid",
                data_format=None,
                dilation_rate=(1, 1),
                groups=1,
                activation=None,
                use_bias=False,
                kernel_initializer="glorot_uniform",
                bias_initializer="zeros",
                kernel_regularizer=None,  # loss + среднее значение модулей весов ядра свертки * коэф
                bias_regularizer=None,    # loss
                activity_regularizer=None,# loss
                kernel_constraint=None,
                bias_constraint=None,
                input_shape=(inp.shape)))
                # **kwargs   

model.compile()
model.summary()

Model: "sequential_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_28 (Conv2D)           (None, 4, 4, 1)           4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
model.set_weights([custom_weights])
model.get_weights()

[array([[[[0.]],
 
         [[1.]]],
 
 
        [[[2.]],
 
         [[3.]]]], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[ 35.  41.  47.  53.]
 [ 65.  71.  77.  83.]
 [ 95. 101. 107. 113.]
 [125. 131. 137. 143.]]


# bias_constraint

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1,
    kernel_size=(2,2),
    strides=1,
    padding="valid",
    data_format=None,
    dilation_rate=(1, 1),
    groups=1,
    activation=None,
    use_bias=True,
    kernel_initializer="ones",
    bias_initializer="ones",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint='maxnorm',   # MaxNorm, MinMaxNorm, NonNeg, UnitNorm, RadialConstraint, custom
    input_shape=(inp.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_29"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_29 (Conv2D)           (None, 4, 4, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# custom_weights = np.array([[[[0]],[[1]]],[[[2]],[[3]]]])
# model.set_weights([custom_weights])
model.get_weights()

[array([[[[1.]],
 
         [[1.]]],
 
 
        [[[1.]],
 
         [[1.]]]], dtype=float32), array([1.], dtype=float32)]

In [ ]:
res = model.predict(inp.reshape(1,5,5,-1))
print(res.shape, '\n')
print(res[0].squeeze())

(1, 4, 4, 1) 

[[17. 21. 25. 29.]
 [37. 41. 45. 49.]
 [57. 61. 65. 69.]
 [77. 81. 85. 89.]]


# Сonv1D


In [ ]:
inp_1 = np.arange(1, 26)
inp_1 = inp_1.reshape((5,5))
print(inp_1.squeeze())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
model = Sequential()
model.add(Conv1D(filters = 1,
    kernel_size=2,
    strides=1,
    padding="same",
    data_format=None,
    dilation_rate=1,
    groups=1,
    activation=None,
    use_bias=False,
    kernel_initializer="ones",
    bias_initializer="ones",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    input_shape=(inp_1.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_61"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_15 (Conv1D)           (None, 5, 1)              10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [ ]:
res = model.predict(inp_1[None,])
print(res.shape, '\n')
print(res[0])

(1, 5, 1) 

[[ 55.]
 [105.]
 [155.]
 [205.]
 [115.]]


In [ ]:
1 + 2 + 3 +4 +5 +6 +7 + 8 + 9 + 10

55

In [ ]:
6 + 7 + 8 + 9 + 10 + 11 + 12 + 13 + 14 + 15

105

In [ ]:
11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19 + 20

155

In [ ]:
model = Sequential()
model.add(Conv1D(filters = 2,
    kernel_size=2,
    strides=1,
    padding="same",
    data_format=None,
    dilation_rate=1,
    groups=1,
    activation=None,
    use_bias=False,
    kernel_initializer="ones",
    bias_initializer="ones",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    input_shape=(inp_1.shape)))
    # **kwargs   

model.compile()
model.summary()

Model: "sequential_62"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_16 (Conv1D)           (None, 5, 2)              20        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [ ]:
res = model.predict(inp_1[None,])
print(res.shape, '\n')
print(res[0])

(1, 5, 2) 

[[ 55.000008  55.000008]
 [104.999985 104.999985]
 [154.99997  154.99997 ]
 [204.99998  204.99998 ]
 [114.99998  114.99998 ]]
