<a href="https://colab.research.google.com/github/safal207/hello-world/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x = np.float32(1.0) 
x

1.0

In [4]:
y = np.int_([1,2,4]) # массив np
y            

array([1, 2, 4])

In [6]:
z = np.arange(3, dtype=np.uint8) # np массив из 3х значений с с типом uint8
z

array([0, 1, 2], dtype=uint8)

In [7]:
np.array([1, 2, 3], dtype='f')   # переводим массив в тип float32 

array([1., 2., 3.], dtype=float32)

In [8]:
z.astype(float)  # конвертируем uint8 в float

array([0., 1., 2.])

In [10]:
np.int8(z)       # конвертируем float в int8

array([0, 1, 2], dtype=int8)

In [11]:
z.dtype

dtype('uint8')

In [13]:
d = np.dtype(int)
d

dtype('int64')

In [14]:
np.issubdtype(d, np.integer)  #проверка типа int

True

In [15]:
np.issubdtype(d, np.floating) #проверка типа float

False

In [26]:
np.power(100, 9, dtype=np.int64)


1000000000000000000

In [17]:
np.power(100, 8, dtype=np.int32)

1874919424

In [20]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [21]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [27]:
np.iinfo

numpy.iinfo

In [28]:
np.power(100, 100, dtype=np.float64)

1e+200